<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

- **Subsetting** means to select
- **Indexing** means to pick only one element of the list or array 
- **Slicing** refers to picking a range of elements

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [3]:
import numpy as np
py_list= ['a1','a2','b3','b4','c5','c6','d7','d8','e9']
np_array= np.array(py_list)
x=np_array
x[0:3] # (excluding last term)

array(['a1', 'a2', 'b3'], dtype='<U2')

In [4]:
x[0:9:3] #index 0 and every third after it till index 9 (excluding last term)

array(['a1', 'b4', 'd7'], dtype='<U2')

In [5]:
x[3:] # index 3 to the end (excluding last term)

array(['b4', 'c5', 'c6', 'd7', 'd8', 'e9'], dtype='<U2')

In [6]:
x[:4] # index 0 to 4 (excluding last term)

array(['a1', 'a2', 'b3', 'b4'], dtype='<U2')

In [7]:
x[::-1] # Reverses the list 
x[4:0:-1] # Reverses the list from index 0 to 5 (excluding last term)

array(['c5', 'b4', 'b3', 'a2'], dtype='<U2')

## 1.2 Arrays only | Subsetting by masking

In [8]:
npx = np.array([1,2,3,4,5,6,7,8,9,10])
mask = npx >=5
mask

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [9]:
npx[mask] 
# If you input another "array" as the index of the original array, 
# you will get only the 'true' values of the original array

array([ 5,  6,  7,  8,  9, 10])

In [10]:
npx[npx<3] #alternatively can just put the condition straight in as the index

array([1, 2])

In [11]:
npx[~(npx<3)] # ~ is the bitwise NOT operator (what does BITWISE mean?)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
npx[(npx>2) & (npx<7)] # & is the AND operator

array([3, 4, 5, 6])

In [13]:
npx[(npx >3) | (npx < 7)] # | This is the OR operator, in the inclusive sense

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
npx[(npx <3) | (npx > 7)]

array([ 1,  2,  8,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [15]:
py2dx = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np2dx = np.array(py2dx) 
print(py2dx[3],np2dx[3])

[4, 'D'] ['4' 'D']


In [21]:
py2dx[:3][0] # This is some strange syntax it does not yield index 0 to 3, why?

[1, 'A']

In [22]:
np2dx[:3,0] # The first element at index 0 - 3 (position 4)

array(['1', '2', '3'], dtype='<U11')

In [23]:
py2dx[3:6][0] # This does not work also, it only prints out index 3 


[4, 'D']

In [24]:
np2dx[3:6,0] # This only works in np arrays i guess

array(['4', '5', '6'], dtype='<U11')

## 1.4 Growing lists
For the purposes of the mod, we will not grow a np array, but learn how to grow a list. np arrays are used for mathematical operations to every element in the array, but not good for growing as it takes a long time (because it destroys and remakes the whole array) 

**Question**: If i can convert a list to a np array, can i convert an np array to a list, also how to do that?

In [26]:
#One option is multiplication
x = [1,5]*6
x`

[1, 5, 1, 5, 1, 5, 1, 5, 1, 5, 1, 5]

In [27]:
# Another option is just adding the term in []s

x = [1]
x = x + [5]
x = x + [7]
x

[1, 5, 7]

In [29]:
# Can shorten the syntax with += like previously 
x = [2]
x += [4]
x += [6]
x

[2, 4, 6]

In [38]:
# can use .append() as well also append is 1.5 times faster 
x=[1]
x.append(1)
x.append(2*2)
x.append(5)
x

[1, 1, 4, 5]

#### extend() vs append()

In [39]:
#extend() adds the integers or elements individually 
x = [1,2,3]
x.extend([1,3,'A'])
x

[1, 2, 3, 1, 3, 'A']

In [40]:
# Append adds everything inside as 'one' element
y =[1,2,3]
y.append([1,3,'A'])
y

[1, 2, 3, [1, 3, 'A']]

#### Sidenote

In [41]:
x = [1]
x += [2]
x*5
x -= [1]
x
# I guess you cant remove items from lists like this 
# How do you remove items from lists?

TypeError: unsupported operand type(s) for -=: 'list' and 'list'

# Some loose ends

## 1.5 Tuples

Tuples are like lists (multi-type) but they are **immutable** meaning they **cannot** be changed after creation. Also their syntax used `()` instead of `[]`

In [42]:
a = (1,2,3)
print(a[0],a[:3])

1 (1, 2, 3)


In [43]:
a[0] = -1 # This no longer works

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying
Because lists and arrays are mutable objects, they are directiories, and the lists are stored at the same location. 

In [44]:
x = [1,2,3]
y = x # DO NOT do this because this will make y's ID equivalent to x and 
      # any changes in y will be reflected in x. for eg. 

y += [4]
print(y,x)

[1, 2, 3, 4] [1, 2, 3, 4]


In [45]:
#Do this instead

x=[1,2,3]
y = x.copy()
y +=[4]
print(y,x)

[1, 2, 3, 4] [1, 2, 3]
