<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

- **Subsetting** means to select
- **Indexing** means to pick only one element of the list or array 
- **Slicing** refers to picking a range of elements

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [16]:
import numpy as np
py_list= ['a1','a2','b3','b4','c5','c6','d7','d8','e9']
np_array= np.array(py_list)
x=np_array
x[0:3] # (excluding last term)

array(['a1', 'a2', 'b3'], dtype='<U2')

In [18]:
x[0:9:3] #index 0 and every third after it till index 9 (excluding last term)

array(['a1', 'b4', 'd7'], dtype='<U2')

In [12]:
x[3:] # index 3 to the end (excluding last term)

array(['b4', 'c5', 'c6', 'd7', 'd8', 'e9'], dtype='<U2')

In [13]:
x[:4] # index 0 to 4 (excluding last term)

array(['a1', 'a2', 'b3', 'b4'], dtype='<U2')

In [11]:
x[::-1] # Reverses the list 
x[4:0:-1] # Reverses the list from index 0 to 5 (excluding last term)

array(['c5', 'b4', 'b3', 'a2'], dtype='<U2')

## 1.2 Arrays only | Subsetting by masking

In [22]:
npx = np.array([1,2,3,4,5,6,7,8,9,10])
mask = npx >=5
mask

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [23]:
npx[mask] 
# If you input another "array" as the index of the original array, 
# you will get only the 'true' values of the original array

array([ 5,  6,  7,  8,  9, 10])

In [24]:
npx[npx<3] #alternatively can just put the condition straight in as the index

array([1, 2])

In [26]:
npx[~(npx<3)] # ~ is the bitwise NOT operator (what does BITWISE mean?)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
npx[(npx>2) & (npx<7)] # & is the AND operator

array([3, 4, 5, 6])

In [29]:
npx[(npx >3) | (npx < 7)] # | This is the OR operator, in the inclusive sense

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
npx[(npx <3) | (npx > 7)]

array([ 1,  2,  8,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [38]:
py2dx = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np2dx = np.array(py2dx) 
print(py2dx[3],np2dx[3])

[4, 'D'] ['4' 'D']


In [39]:
py2dx[3][0] # The first element at index 3 (position 4)

4

In [40]:
np2dx[3,0] # The first element at index 3 (position 4)

'4'

Difference between numpy array and list: the array use a comma to seperate the values but use more brackets in lists

In [42]:
py2dx[3:6][0]
np2dx[3:6,0] #The difference is here again 

array(['4', '5', '6'], dtype='<U11')

## 1.4 Growing lists

# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

# Exercises & Self-Assessment

In [ ]:
# Your solution here





## Footnotes