<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [4]:
import numpy as np

1. Lists
1. Numpy Arrays
1. Dictionaries
1. Tuples
1. Dataframes (data processing part)
1. Classes (nice chapter)

# 1 Lists, Arrays & Dictionaries

## 1.1 Lets Compare

In [13]:
#This is a python list, just use []
pymods = ['SP2273','HSA1000','HSS1000','DTK1234','PC1101','MA2001']

In [14]:
#This is a numpy array use 'np.array' 
np.mods = np.array(['SP2273','HSA1000','HSS1000','DTK1234','PC1101','MA2001'])

In [15]:
#This is a dictionary the associated value is seperated using : it kind of 
#stores "two" arrays as one and the ORDER MATTERS. mods[0] must have its
#equivalent value in the 0th slot as well. does not apply for dictionaries.

mods_subject={
    'Physics':'PC1101',
    'Math': 'MA2001',
    'SPS':'SP2273',
    'CHS':'HSS1000'
}

## 1.2 Accessing data from a list (or array)

In [20]:
#Python lists always starts counting from the 0th term
pymods[0]

'SP2273'

In [19]:
#you can use '-1' to count from the back as well
#For when we don't know the total number of terms in the list
pymods[-1]

'MA2001'

## 1.3 Accessing data from a dictionary

In [23]:
#You access the corresponding term using the 'key' which is the 
#Value on the left of the :
mods_subject['Math']

'MA2001'

In [24]:
#In order to access all the keys
mods_subject.keys()

dict_keys(['Physics', 'Math', 'SPS', 'CHS'])

In [25]:
#In order to access all the corresponding values
mods_subject.values()

dict_values(['PC1101', 'MA2001', 'SP2273', 'HSS1000'])

## 1.4 Higher dimensional lists

In [31]:
#For higher dimensional arrays use multiple []s

modsarray=[['physics','PC1101'],
           ['math','MA2001'],
           ['chem','CM1102'],
           ['CHS','DTK1234']]
modsarray[0] 
#Do both values have to be called together? 
#Like can I somehow get 'CHS','MA2001' using 2D arrays?

['physics', 'PC1101']

# 2 Lists vs. Arrays

## 2.1 Size

In [6]:
#Use the function len() to figure out the size of the list or the array.

list2d = [[1,'a'],
        [2,'b'],
        [3,'c'],
        [4,'d']]
array2d = np.array(list2d) 
#Converting the py list into a np array
# Why cant i name my variable starting with an integer like '2dlist'? 
# It keeps giving me an error
# Its just a syntax thing and part of the way python parses variable names 

In [3]:
len(list2d)

4

In [39]:
len(array2d)

4

In [7]:
array2d.shape
#shape is not a function but a property/ attribute? 
#I dont understand what this means

<class 'tuple'>


In [48]:
test3d = [[['a','b','c'], ['e','f','g']]]
array3d= np.array(test3d)
array3d.shape
#what does this result even mean LOL 
# This gives the distance of the dimentions of the array. 

(1, 2, 3)

In [10]:
x = [ 1, [1, 2, [4, 7], 5], 6 , [1, 4]]
y = np.array(x)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

For the one above, there are 4 elements in the 'vector' but each vector is a different size

In [16]:
x = [[[1, 2],[3,4], [4, 7]], [[1, 2],[3,4], [4, 7]]]
# Because numpy arrays use vectorised operations, it is like a 3x3 matrix with each element of the matrix being a matrix of a different side. 
# Hence numpy cannot store the array properly if the dimensions within each [] of the array is different
y = np.array(x)
y.shape 
# Gives you the 'width' of each dimension like [4,7] is 2, there are 3 of such 2 element lists in the second dimension and 
# total of 2 lists in this array

(2, 3, 2)

## 2.2 Arrays are fussy about type

In [50]:
#Numpy arrays only tolerate ONE type. meaning all integers muust be all integers
py_list =[1,2,3,4,1.5,'A']
np_array=np.array(py_list)
py_list

[1, 2, 3, 4, 1.5, 'A']

In [53]:
np_array
# So all the values have been converted into strings 
# What does 'dtype="<U32"' mean?

array(['1', '2', '3', '4', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [91]:
x = [1,2,3,4,5,6]
npx = np.array(x)

In [56]:
#Arrays work like mathematical objects
npx + 10 

array([11, 12, 13, 14, 15, 16])

In [57]:
x + 10 # This doesnt work

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [58]:
x2=[10,10,10,10,10,10]
npx2 = np.array(x2)

In [60]:
# Summing lists just adds the two groups together
x+ x2

[1, 2, 3, 4, 5, 6, 10, 10, 10, 10, 10, 10]

In [62]:
npx + npx2 
# Adding arrays is like a mathematical operation,
#Adding 0th term to the 0th terms

array([11, 12, 13, 14, 15, 16])

## 2.5 Multiplying by a Number

In [64]:
#Same explaination as above for lists vs arrays 
print(x*2,x2*2)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6] [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]


In [73]:
print(npx*2,'\n',npx2*2)
#Why are they misaligned haha

[ 2  4  6  8 10 12] 
 [20 20 20 20 20 20]


## 2.6 Squaring

In [74]:
#You can't square a list
x**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [75]:
npx**2 
#just does the mathematical operation to every term in the array 
#Just as you expect it to

array([ 1,  4,  9, 16, 25, 36])

## 2.7 Asking questions

In [77]:
x == 3

False

In [78]:
x == 6

False

In [88]:
x == [1,2,3,4,5,6] # Its comparing if the entire list is identical 

True

In [93]:
npx == 3 #Tests if each term of the array is equal to that number

array([False, False,  True, False, False, False])

In [95]:
npx >= 3 # Works the same for any mathematical conditional

array([False, False,  True,  True,  True,  True])

## 2.8 Mathematics

### 2.8.1 Lists

In [99]:
print(sum(x),min(x),max(x)) #All quite self explainatory

21 1 6


In [100]:
x.sum() #This does not work but it needs to be an array for this to work

AttributeError: 'list' object has no attribute 'sum'

In [103]:
print(npx.sum(),npx.max(),npx.min(),npx.mean(), npx.std())
#Also all quite self explainatory just that you put '.function()' unlike lists
# Also std is sample standard deviation not variance

21 6 1 3.5 1.707825127659933


Generally operations works on the whole **list** and takes it as **one object** while **arrays** operates on **every element** in the array individually.


## Footnotes